In [1]:
import pandas as pd

In [2]:
rules_table = pd.read_html('../docs/rules.html')[0]

In [3]:
rules_table

,Attribute Name,Tag,Retired (from PS3.6),In Std. Comp. IOD (from PS3.3),Basic Profile,Retain Safe Private Option,Retain UIDs Option,Retain Device Ident. Option,Retain Patient Chars. Option,Retain Long. Full Dates Option,Retain Long. Modif. Dates Option,Clean Desc. Option,Clean Struct. Cont. Option,Clean Graph. Option
0,Accession Number,"(0008,0050)",N,Y,Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Acquisition Comments,"(0018,4000)",Y,N,X,NaN,NaN,NaN,NaN,NaN,NaN,C,NaN,NaN
2,Acquisition Context Sequence,"(0040,0555)",N,Y,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,NaN
3,Acquisition Date,"(0008,0022)",N,Y,X/Z,NaN,NaN,NaN,NaN,K,C,NaN,NaN,NaN
4,Acquisition DateTime,"(0008,002A)",N,Y,X/D,NaN,NaN,NaN,NaN,K,C,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,Verifying Observer Identification Code Sequence,"(0040,A088)",N,Y,Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,Verifying Observer Name,"(0040,A075)",N,Y,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,Verifying Observer Sequence,"(0040,A073)",N,Y,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,Verifying Organization,"(0040,A027)",N,Y,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,Visit Comments,"(0038,4000)",N,N,X,NaN,NaN,NaN,NaN,NaN,NaN,C,NaN,NaN

Following rules needs to applied for each selected tags:

* D - replace with a non-zero length value that may be a dummy value and consistent with the VR ([Value Representation](https://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html))
* Z - replace with a zero length value, or a non-zero length value that may be a dummy value and consistent with the VR
* X - remove
* K - keep (unchanged for non-sequence attributes, cleaned for sequences)
* C - clean, that is replace with values of similar meaning known not to contain identifying information and consistent with the VR
* U - replace with a non-zero length UID that is internally consistent within a set of Instances
* Z/D - Z unless D is required to maintain IOD conformance (Type 2 versus Type 1)
* X/Z - X unless Z is required to maintain IOD conformance (Type 3 versus Type 2)
* X/D - X unless D is required to maintain IOD conformance (Type 3 versus Type 1)
* X/Z/D - X unless Z or D is required to maintain IOD conformance (Type 3 versus Type 2 versus Type 1)
* X/Z/U* - X unless Z or replacement of contained instance UIDs (U) is required to maintain IOD conformance (Type 3 versus Type 2 versus Type 1 sequences containing UID references)

In [4]:
basic_profile_rules = rules_table[['Attribute Name', 'Tag', 'Basic Profile']]

In [5]:
basic_profile_rules

,Attribute Name,Tag,Basic Profile
0,Accession Number,"(0008,0050)",Z
1,Acquisition Comments,"(0018,4000)",X
2,Acquisition Context Sequence,"(0040,0555)",X
3,Acquisition Date,"(0008,0022)",X/Z
4,Acquisition DateTime,"(0008,002A)",X/D
...,...,...,...
244,Verifying Observer Identification Code Sequence,"(0040,A088)",Z
245,Verifying Observer Name,"(0040,A075)",D
246,Verifying Observer Sequence,"(0040,A073)",D
247,Verifying Organization,"(0040,A027)",X
248,Visit Comments,"(0038,4000)",X

### Get all the UID

In [6]:
basic_profile_rules[basic_profile_rules['Basic Profile'] == 'U']

,Attribute Name,Tag,Basic Profile
22,Concatenation UID,"(0020,9161)",U
29,Context Group Extension Creator UID,"(0008,010D)",U
33,Creator Version UID,"(0008,9123)",U
43,Device UID,"(0018,1002)",U
46,Dimension Organization UID,"(0020,9164)",U
50,Dose Reference UID,"(300A,0013)",U
52,Failed SOP Instance UID List,"(0008,0058)",U
53,Fiducial UID,"(0070,031A)",U
56,Frame of Reference UID,"(0020,0052)",U
68,Instance Creator UID,"(0008,0014)",U
82,Irradiation Event UID,"(0008,3010)",U
86,Large Palette Color Lookup Table UID,"(0028,1214)",U
89,Media Storage SOP Instance UID,"(0002,0003)",U
113,Palette Color Lookup Table UID,"(0028,1199)",U
166,Referenced Frame of Reference UID,"(3006,0024)",U
167,Referenced General Purpose Scheduled Procedure...,"(0040,4023)",U
173,Referenced SOP Instance UID,"(0008,1155)",U
174,Referenced SOP Instance UID in File,"(0004,1511)",U
181,Related Frame of Reference UID,"(3006,00C2)",U
188,Requested SOP Instance UID,"(0000,1001)",U
215,Series Instance UID,"(0020,000E)",U
220,SOP Instance UID,"(0008,0018)",U
224,Storage Media File-set UID,"(0088,0140)",U
230,Study Instance UID,"(0020,000D)",U
232,Synchronization Frame of Reference UID,"(0020,0200)",U
233,Template Extension Creator UID,"(0040,DB0D)",U
234,Template Extension Organization UID,"(0040,DB0C)",U
242,Transaction UID,"(0008,1195)",U
243,UID,"(0040,A124)",U

In [7]:
basic_profile_rules[basic_profile_rules['Attribute Name'].str.contains('UID')]

,Attribute Name,Tag,Basic Profile
15,Affected SOP Instance UID,"(0000,1000)",X
22,Concatenation UID,"(0020,9161)",U
29,Context Group Extension Creator UID,"(0008,010D)",U
33,Creator Version UID,"(0008,9123)",U
43,Device UID,"(0018,1002)",U
44,Digital Signature UID,"(0400,0100)",X
46,Dimension Organization UID,"(0020,9164)",U
50,Dose Reference UID,"(300A,0013)",U
52,Failed SOP Instance UID List,"(0008,0058)",U
53,Fiducial UID,"(0070,031A)",U
56,Frame of Reference UID,"(0020,0052)",U
68,Instance Creator UID,"(0008,0014)",U
82,Irradiation Event UID,"(0008,3010)",U
86,Large Palette Color Lookup Table UID,"(0028,1214)",U
89,Media Storage SOP Instance UID,"(0002,0003)",U
113,Palette Color Lookup Table UID,"(0028,1199)",U
166,Referenced Frame of Reference UID,"(3006,0024)",U
167,Referenced General Purpose Scheduled Procedure...,"(0040,4023)",U
173,Referenced SOP Instance UID,"(0008,1155)",U
174,Referenced SOP Instance UID in File,"(0004,1511)",U
181,Related Frame of Reference UID,"(3006,00C2)",U
188,Requested SOP Instance UID,"(0000,1001)",U
215,Series Instance UID,"(0020,000E)",U
220,SOP Instance UID,"(0008,0018)",U
224,Storage Media File-set UID,"(0088,0140)",U
230,Study Instance UID,"(0020,000D)",U
232,Synchronization Frame of Reference UID,"(0020,0200)",U
233,Template Extension Creator UID,"(0040,DB0D)",U
234,Template Extension Organization UID,"(0040,DB0C)",U
242,Transaction UID,"(0008,1195)",U
243,UID,"(0040,A124)",U

### Get the Dates

In [8]:
basic_profile_rules[basic_profile_rules['Attribute Name'].str.contains('Date')]

                          Attribute Name          Tag Basic Profile
3                       Acquisition Date  (0008,0022)           X/Z
4                   Acquisition DateTime  (0008,002A)           X/D
11                        Admitting Date  (0038,0020)             X
26                          Content Date  (0008,0023)           Z/D
36                            Curve Date  (0008,0025)             X
87                   Last Menstrual Date  (0010,21D0)             X
111                         Overlay Date  (0008,0024)             X
122                 Patient's Birth Date  (0010,0030)             Z
138    Performed Procedure Step End Date  (0040,0250)             X
141  Performed Procedure Step Start Date  (0040,0244)             X
201    Scheduled Procedure Step End Date  (0040,0004)             X
205  Scheduled Procedure Step Start Date  (0040,0002)             X
213                          Series Date  (0008,0021)           X/D
226                           Study Date  (0008,0020)             Z